service: portfolio

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  apiName: portfolio

functions:
  api:
    handler: server/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
