service: portfolio

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  apiName: portfolio

functions:
  api:
    handler: dist/server/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
